# Generated by Django 5.0.2 on 2025-04-26 13:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('ANX', 'Anxiety'), ('DEP', 'Depression'), ('MIN', 'Mindfulness'), ('STR', 'Work Stress'), ('REL', 'Relationships'), ('CAR', 'Self-Care'), ('SLE', 'Sleep'), ('THR', 'Therapy'), ('EXE', 'Exercise')], max_length=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-binary')], max_length=1)),
                ('primary_focus', models.CharField(choices=[('ANX', 'Anxiety'), ('DEP', 'Depression'), ('STR', 'Stress'), ('REL', 'Relationships'), ('SLE', 'Sleep'), ('MIN', 'Mindfulness'), ('GEN', 'General Support')], max_length=3)),
                ('specific_concerns', models.TextField()),
                ('additional_context', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
