# Generated by Django 5.0.2 on 2025-04-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='avatar',
            field=models.CharField(choices=[('/static/main/avatars/avatar1.png', 'Blue Bot'), ('/static/main/avatars/avatar2.png', 'Green Bot'), ('/static/main/avatars/avatar3.png', 'Purple Bot'), ('/static/main/avatars/avatar4.png', 'Orange Bot'), ('/static/main/avatars/avatar5.png', 'Pink Bot')], default='/static/main/avatars/avatar1.png', max_length=100),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='personality',
            field=models.CharField(choices=[('empathetic', 'Empathetic Listener'), ('motivational', 'Motivational Coach'), ('calm', 'Calm Supporter'), ('cheerful', 'Cheerful Friend'), ('practical', 'Practical Advisor')], default='empathetic', max_length=20),
        ),
    ]
